# 项目相关配置
vainglory:
  # 名称
  name: Vainglory
  # 版本
  version: 0.1.0
  # 作者
  author: lid
  # 版权
  copyright: 2025
  # 文件路径 示例（ Windows配置D:/vainglory/uploadPath，Linux配置 /home/vainglory/uploadPath）
  basePath: /home/vainglory/
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数字计算 char 字符验证
  captchaType: math


server:
  port: 8888
  servlet:
    context-path: /vg/v1




# Spring配置
spring:
  application:
    name: ${vainglory.name}
  threads:
    virtual:
      enabled: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 10
      auto-commit: true
      idle-timeout: 600000
      pool-name: MyHikariCP
      max-lifetime: 1800000
    url: jdbc:postgresql://localhost:5432/vainglory
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver




mybatis-plus:
  checkConfigLocation: false
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  type-aliases-package: com.vainglory.domain
  configuration:
    # 自动驼峰命名规则（camel case）映射
    mapUnderscoreToCamelCase: true
    # MyBatis 自动映射策略
    # NONE：不启用 PARTIAL：只对非嵌套 resultMap 自动映射 FULL：对所有 resultMap 自动映射
    autoMappingBehavior: FULL
    # MyBatis 自动映射时未知列或未知属性处理策
    # NONE：不做处理 WARNING：打印相关警告 FAILING：抛出异常和详细信息
    autoMappingUnknownColumnBehavior: NONE
    # 更详细的日志输出 会有性能损耗 org.apache.ibatis.logging.stdout.StdOutImpl
    # 关闭日志记录 (可单纯使用 p6spy 分析) org.apache.ibatis.logging.nologging.NoLoggingImpl
    # 默认日志输出 org.apache.ibatis.logging.slf4j.Slf4jImpl
    logImpl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config:
    banner: false
    dbConfig:
      id-type: assign_uuid
      schema: public
      # 逻辑已删除值(可按需求随意修改)
      logicDeleteValue: 'now()'
      # 逻辑未删除值
      logicNotDeleteValue: 'null'
